name: Docs

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    container:
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Install Dependencies
      run: shards install
    - name: Lint
      run: ./bin/ameba
    - name: Build Docs
      run: |
        pip3 install -r requirements.txt
        mkdocs gh-deploy --force
      env:
        GH_TOKEN: ${{ secrets.GHUB_PAT }}
