name: Docs

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    
    container:
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install Crystal Dependencies
      run: shards install
    - name: Lint
      run: ./bin/ameba
    - name: Build Docs
      run: mkdocs build
    - name: Deploy to GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v2
      with:
        keep_history: true
        build_dir: site
        committer_name: Chris Watson
        committer_email: cawatson1993@gmail.com
        commit_message: "Update docs"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
