name: Docs

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    container:
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: shards install
    - name: Lint
      run: ./bin/ameba
    - name: Pipenv Install
      uses: VaultVulp/action-pipenv@v2.0.1
      with:
        command: install -d
    - name: Build Docs
      run: mkdocs gh-deploy --force
      env:
        GH_TOKEN: ${{ secrets.GHUB_PAT }}
