name: Docs

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    container:
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: shards install
    - name: Lint
      run: ./bin/ameba
    - name: Build Docs
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      run: |
        pip install -r requirements.txt
        mkdocs gh-deploy --force
      env:
        GH_TOKEN: ${{ secrets.GHUB_PAT }}
